// <auto-generated />
using System;
using Doantotnghiep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Doantotnghiep.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602172301_deletecalamviec")]
    partial class deletecalamviec
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Doantotnghiep.Models.Entities.ChiTietDatLich", b =>
                {
                    b.Property<int>("IdChiTietDatLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChiTietDatLich"));

                    b.Property<decimal>("GiaDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdDatLich")
                        .HasColumnType("int");

                    b.Property<int>("IdDichVu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdChiTietDatLich");

                    b.HasIndex("IdDatLich");

                    b.HasIndex("IdDichVu");

                    b.ToTable("ChiTietDatLiches");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("IdChiTietHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChiTietHoaDon"));

                    b.Property<decimal>("DonGiaDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdDichVu")
                        .HasColumnType("int");

                    b.Property<int>("IdHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDV")
                        .HasColumnType("int");

                    b.Property<decimal>("TienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdChiTietHoaDon");

                    b.HasIndex("IdDichVu");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdKhuyenMai");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.DatLich", b =>
                {
                    b.Property<int>("IdDatLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDatLich"));

                    b.Property<int?>("DichVuIdDichVu")
                        .HasColumnType("int");

                    b.Property<string>("GhiChuDatLich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GioBatDauDV")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GioKetThucDV")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatDatLich")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHenLich")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoDatLich")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiDatLich")
                        .HasColumnType("int");

                    b.HasKey("IdDatLich");

                    b.HasIndex("DichVuIdDichVu");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("DatLichs");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.DichVu", b =>
                {
                    b.Property<int>("IdDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDichVu"));

                    b.Property<string>("CongCuSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnhDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLoaiDichVu")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LieuTrinhDichVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LuuYKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTaoDichVu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoaDV")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguyenLieuSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuyTrinhThucHien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiLuongDV")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThaiDV")
                        .HasColumnType("bit");

                    b.HasKey("IdDichVu");

                    b.HasIndex("IdLoaiDichVu");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.DichVuKhuyenMai", b =>
                {
                    b.Property<int>("IdDichVuKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDichVuKhuyenMai"));

                    b.Property<int>("IdDichVu")
                        .HasColumnType("int");

                    b.Property<int>("IdKhuyenMai")
                        .HasColumnType("int");

                    b.HasKey("IdDichVuKhuyenMai");

                    b.HasIndex("IdDichVu");

                    b.HasIndex("IdKhuyenMai");

                    b.ToTable("DichVuKhuyenMais");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.HoaDon", b =>
                {
                    b.Property<int>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoaDon"));

                    b.Property<int>("IdDatLich")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTaoHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhuongThucTT")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTienGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienSauGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThaiHoaDon")
                        .HasColumnType("int");

                    b.HasKey("IdHoaDon");

                    b.HasIndex("IdDatLich");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.HoiThoaiAI", b =>
                {
                    b.Property<int>("IdHoiThoaiAI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoiThoaiAI"));

                    b.Property<bool>("CanNhanVienTuVan")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChuNoiBo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiHoiThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHoiThoaiAI");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("HoiThoaiAIs");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.KhachHang", b =>
                {
                    b.Property<int>("IdKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhachHang"));

                    b.Property<string>("DiaChiKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayTaoKH")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoaKH")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhachHang");

                    b.HasIndex("IdTaiKhoan")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.KhuyenMai", b =>
                {
                    b.Property<int>("IdKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhuyenMai"));

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiKhuyenMai")
                        .HasColumnType("int");

                    b.Property<string>("MoTaKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhatKhuyenMai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoKhuyenMai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoaKhuyenMai")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiKhuyenMai")
                        .HasColumnType("bit");

                    b.HasKey("IdKhuyenMai");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.LoaiDichVu", b =>
                {
                    b.Property<int>("IdLoaiDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoaiDichVu"));

                    b.Property<string>("MoTaLoaiDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTaoLoaiDichVu")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLoaiDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiLoaiDV")
                        .HasColumnType("bit");

                    b.HasKey("IdLoaiDichVu");

                    b.ToTable("LoaiDichVus");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.LoaiTriThuc", b =>
                {
                    b.Property<int>("IdLoaiTriThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoaiTriThuc"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MoTaLoaiTriThuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhatLoaiTriThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoLoaiTriThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoaLoaiTriThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLoaiTriThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLoaiTriThuc");

                    b.ToTable("LoaiTriThucs");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.NhanVien", b =>
                {
                    b.Property<int>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhanVien"));

                    b.Property<string>("ChuyenMonNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("GioBatDauLamViec")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThucLamViec")
                        .HasColumnType("time");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LaNhanVienFullTime")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayTaoNV")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoaNV")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThaiNV")
                        .HasColumnType("int");

                    b.HasKey("IdNhanVien");

                    b.HasIndex("IdTaiKhoan")
                        .IsUnique();

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.NhanVienDichVu", b =>
                {
                    b.Property<int>("IdNhanVienDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhanVienDichVu"));

                    b.Property<int>("IdDichVu")
                        .HasColumnType("int");

                    b.Property<int>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThaiNVDV")
                        .HasColumnType("bit");

                    b.HasKey("IdNhanVienDichVu");

                    b.HasIndex("IdDichVu");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("NhanVienDichVus");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdVaiTro")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayTaoTaiKhoan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoaTaiKhoan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiTK")
                        .HasColumnType("bit");

                    b.HasKey("IdTaiKhoan");

                    b.HasIndex("IdVaiTro");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.ThongBao", b =>
                {
                    b.Property<int>("IdThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongBao"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThongBao");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.TinNhanAI", b =>
                {
                    b.Property<int>("IdTinNhanAI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTinNhanAI"));

                    b.Property<int>("IdHoiThoaiAI")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("thoiGianGui")
                        .HasColumnType("datetime2");

                    b.HasKey("IdTinNhanAI");

                    b.HasIndex("IdHoiThoaiAI");

                    b.ToTable("TinNhanAIs");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.TriThuc", b =>
                {
                    b.Property<int>("IdTriThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTriThuc"));

                    b.Property<int>("IdLoaiTriThuc")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhatTriThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhapTriThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoaTriThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungTriThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTriThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiTriThuc")
                        .HasColumnType("bit");

                    b.Property<string>("TuKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTriThuc");

                    b.HasIndex("IdLoaiTriThuc");

                    b.ToTable("TriThucs");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.VaiTro", b =>
                {
                    b.Property<int>("IdVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVaiTro");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.ChiTietDatLich", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.DatLich", "DatLich")
                        .WithMany("ChiTietDatLichs")
                        .HasForeignKey("IdDatLich")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Doantotnghiep.Models.Entities.DichVu", "DichVu")
                        .WithMany("ChiTietDatLichs")
                        .HasForeignKey("IdDichVu")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DatLich");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.DichVu", "DichVu")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IdDichVu")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Doantotnghiep.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Doantotnghiep.Models.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IdKhuyenMai");

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.DatLich", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.DichVu", null)
                        .WithMany("DatLiches")
                        .HasForeignKey("DichVuIdDichVu");

                    b.HasOne("Doantotnghiep.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DatLiches")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Doantotnghiep.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("DatLiches")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.DichVu", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.LoaiDichVu", "LoaiDichVu")
                        .WithMany("DichVus")
                        .HasForeignKey("IdLoaiDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiDichVu");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.DichVuKhuyenMai", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.DichVu", "DichVu")
                        .WithMany("DichVuKhuyenMais")
                        .HasForeignKey("IdDichVu")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Doantotnghiep.Models.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("DichVuKhuyenMais")
                        .HasForeignKey("IdKhuyenMai")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.HoaDon", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.DatLich", "DatLich")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdDatLich")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DatLich");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.HoiThoaiAI", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("HoiThoaiAIs")
                        .HasForeignKey("IdKhachHang");

                    b.HasOne("Doantotnghiep.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("HoiThoaiAIs")
                        .HasForeignKey("IdNhanVien");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.KhachHang", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("Doantotnghiep.Models.Entities.KhachHang", "IdTaiKhoan")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.NhanVien", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVien")
                        .HasForeignKey("Doantotnghiep.Models.Entities.NhanVien", "IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.NhanVienDichVu", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.DichVu", "DichVu")
                        .WithMany("NhanVienDichVus")
                        .HasForeignKey("IdDichVu")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Doantotnghiep.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("NhanVienDichVus")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("IdVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.ThongBao", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang");

                    b.HasOne("Doantotnghiep.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IdNhanVien");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.TinNhanAI", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.HoiThoaiAI", "HoiThoaiAI")
                        .WithMany("TinNhanAIs")
                        .HasForeignKey("IdHoiThoaiAI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoiThoaiAI");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.TriThuc", b =>
                {
                    b.HasOne("Doantotnghiep.Models.Entities.LoaiTriThuc", "LoaiTriThuc")
                        .WithMany("TriThucs")
                        .HasForeignKey("IdLoaiTriThuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiTriThuc");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.DatLich", b =>
                {
                    b.Navigation("ChiTietDatLichs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.DichVu", b =>
                {
                    b.Navigation("ChiTietDatLichs");

                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("DatLiches");

                    b.Navigation("DichVuKhuyenMais");

                    b.Navigation("NhanVienDichVus");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.HoiThoaiAI", b =>
                {
                    b.Navigation("TinNhanAIs");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("DatLiches");

                    b.Navigation("HoiThoaiAIs");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.KhuyenMai", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("DichVuKhuyenMais");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.LoaiDichVu", b =>
                {
                    b.Navigation("DichVus");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.LoaiTriThuc", b =>
                {
                    b.Navigation("TriThucs");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.NhanVien", b =>
                {
                    b.Navigation("DatLiches");

                    b.Navigation("HoiThoaiAIs");

                    b.Navigation("NhanVienDichVus");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Doantotnghiep.Models.Entities.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
